CREATE OR ALTER TRIGGER LOTE_ENTRADA FOR MOVIMENTODETALHE ACTIVE
AFTER UPDATE POSITION 1
as
  DECLARE VARIABLE QTDEESTOQ DOUBLE PRECISION; 
  DECLARE VARIABLE ESTOQATUAL DOUBLE PRECISION; 
  DECLARE VARIABLE TEMLOTE VARCHAR(60); 
  DECLARE VARIABLE TIPO VARCHAR(20); 
  DECLARE VARIABLE PRECO DOUBLE PRECISION; 

begin
 /* 0 = ENTRADA */
 /* Adiciono a Quantidade Comprada ou Entrada na Tab Lote */
 if (NEW.BAIXA = '0') then
   IF (OLD.LOTE <> '') THEN
   BEGIN
     TIPO = 'GERAL';
     SELECT DADOS FROM PARAMETRO WHERE PARAMETRO = 'EMPRESA'
       INTO :TIPO;

     PRECO = NEW.PRECO;
     IF (TIPO = 'CITRUS') THEN
        PRECO = NEW.COD_COMISSAO; -- Cod. do Fornecedor (e usado na venda e lancamento colheira e frete)
         
     /* Procuro na tabela LOTES se ja existe */
     SELECT FIRST 1 ESTOQUE, LOTE FROM LOTES WHERE LOTE = OLD.LOTE 
       AND CODPRODUTO = OLD.CODPRODUTO 
     INTO :ESTOQATUAL, :TEMLOTE;

       IF (TEMLOTE IS NULL) THEN
       BEGIN
         IF (ESTOQATUAL IS NULL) THEN 
            ESTOQATUAL = 0;
         INSERT INTO LOTES(LOTE, CODPRODUTO, DATAFABRICACAO, DATAVENCIMENTO, ESTOQUE, PRECO, NOTAFISCAL) 
           VALUES(OLD.LOTE, old.CODPRODUTO, OLD.DTAFAB, OLD.DTAVCTO, OLD.QUANTIDADE, :PRECO, OLD.NOTAFISCAL);
       end 
       ELSE BEGIN
         IF (ESTOQATUAL IS NULL) THEN 
            ESTOQATUAL = 0;
         QTDEESTOQ = ESTOQATUAL + OLD.QUANTIDADE;
         UPDATE LOTES SET ESTOQUE = :QTDEESTOQ, PRECO = :PRECO WHERE LOTE = OLD.LOTE
           AND CODPRODUTO = OLD.CODPRODUTO;
       END

   end
end
