CREATE OR ALTER PROCEDURE SP_CONTAS_REC_GERAIS (
    DTAINI DATE,
    DTAFIM DATE)
RETURNS (
    DTAEMISSAO DATE,
    DTAVENC DATE,
    CODCLI INTEGER,
    CLIENTES VARCHAR(60),
    DESCRICAO VARCHAR(150),
    VALORTITULO DOUBLE PRECISION,
    VALORPAGO DOUBLE PRECISION,
    CONTACONTABIL VARCHAR(100),
    CAIXA VARCHAR(60),
    CODCONTA VARCHAR(15))
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE N_TITULO VARCHAR(15);
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN



  /* Lista as contas a receber e recebidas gerais */


  FOR SELECT rec.EMISSAO ,rec.DATAVENCIMENTO, CAST(rec.CODCLIENTE AS VARCHAR(5)) || '-' ||  cli.NOMECLIENTE,
    rec.HISTORICO, rec.valor_prim_via, rec.VALORRECEBIDO, rec.CONTACREDITO,rec.CAIXA
    FROM RECEBIMENTO rec, CLIENTES cli where cli.CODCLIENTE = rec.CODCLIENTE
    and rec.EMISSAO BETWEEN :DTAINI AND :DTAFIM and rec.valor_prim_via > 0 order by rec.EMISSAO
  INTO :DTAEMISSAO, :DTAVENC, :CLIENTES, :DESCRICAO, :VALORTITULO, :VALORPAGO, :CCONTABIL, :CCAIXA
  DO BEGIN

    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;



    SUSPEND;
    contacontabil = null;
  END
END
