/******************************************************************************/
/****              Generated by IBExpert 19/01/2012 17:03:35               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE LAN_DMED (
    COD_CLIENTE     INTEGER,
    COD_FORNECEDOR  INTEGER,
    NOMEFORNECEDOR  VARCHAR(60),
    TIPOFIRMA       SMALLINT,
    CNPJ            VARCHAR(18),
    DESCRICAO       VARCHAR(60),
    CODPRO          VARCHAR(15),
    PRODUTO         VARCHAR(300),
    NUMEROBORDERO   INTEGER,
    CODVENDA1       INTEGER,
    NOMECLIENTE1    VARCHAR(50),
    PRECO           DOUBLE PRECISION,
    RAZAOSOCIAL     VARCHAR(50),
    VALOR_RECIBO    DOUBLE PRECISION
);




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

