CREATE PROCEDURE GUIA (
    razao varchar(70),
    dta1 date,
    dta2 date)
returns (
    id_guias integer,
    numero_guia varchar(20),
    data_emissao date,
    nome_funcionario varchar(70),
    nome_empresa varchar(70),
    nome_executante varchar(100),
    sigla_conselho varchar(7),
    numero_profissional varchar(15),
    sigla_unidade varchar(2),
    codigo_especialidade varchar(5),
    codigo_cid10_1 varchar(5),
    codigo_cid10_2 varchar(5),
    codigo_cid10_3 varchar(5),
    codigo_cid10_4 varchar(5),
    data_atendimento date,
    grau_risco varchar(2),
    tipo_consulta varchar(1),
    apto integer,
    observacao varchar(240),
    tipo_guia varchar(20),
    codcliente integer,
    tipo char(1),
    rg varchar(24),
    cpf varchar(14),
    cargo varchar(60),
    funcao varchar(60),
    pis varchar(20),
    data1 date,
    ck1 char(1),
    exame1 varchar(60),
    cka1 char(1),
    alterado1 varchar(60),
    data2 date,
    ck2 char(1),
    exame2 varchar(60),
    cka2 char(1),
    alterado2 varchar(60),
    data3 date,
    ck3 char(1),
    exame3 varchar(60),
    cka3 char(1),
    alterado3 varchar(60),
    data4 date,
    ck4 char(1),
    exame4 varchar(60),
    cka4 char(1),
    alterado4 varchar(60),
    data5 date,
    ck5 char(1),
    exame5 varchar(60),
    cka5 char(1),
    alterado5 varchar(60),
    data6 date,
    ck6 char(1),
    exame6 varchar(60),
    cka6 char(1),
    alterado6 varchar(60),
    data7 date,
    ck7 char(1),
    exame7 varchar(60),
    cka7 char(1),
    alterado7 varchar(60),
    data8 date,
    ck8 char(1),
    exame8 varchar(60),
    cka8 char(1),
    alterado8 varchar(60),
    data9 date,
    ck9 char(1),
    exame9 varchar(60),
    cka9 char(1),
    alterado9 varchar(60),
    data10 date,
    ck10 char(1),
    exame10 varchar(60),
    cka10 char(1),
    alterado10 varchar(60),
    data11 date,
    ck11 char(1),
    exame11 varchar(60),
    cka11 char(1),
    alterado11 varchar(60),
    data12 date,
    ck12 char(1),
    exame12 varchar(60),
    cka12 char(1),
    alterado12 varchar(60),
    data13 date,
    ck13 char(1),
    exame13 varchar(60),
    cka13 char(1),
    alterado13 varchar(60),
    data14 date,
    ck14 char(1),
    exame14 varchar(60),
    cka14 char(1),
    alterado14 varchar(60),
    data15 date,
    ck15 char(1),
    exame15 varchar(60),
    cka15 char(1),
    alterado15 varchar(60),
    data16 date,
    ck16 char(1),
    exame16 varchar(60),
    cka16 char(1),
    alterado16 varchar(60),
    data17 date,
    ck17 char(1),
    exame17 varchar(60),
    cka17 char(1),
    alterado17 varchar(60),
    data18 date,
    ck18 char(1),
    exame18 varchar(60),
    cka18 char(1),
    alterado18 varchar(60),
    data19 date,
    ck19 char(1),
    exame19 varchar(60),
    cka19 char(1),
    alterado19 varchar(60),
    data20 date,
    ck20 char(1),
    exame20 varchar(60),
    cka20 char(1),
    alterado20 varchar(60),
    data21 date,
    ck21 char(1),
    exame21 varchar(60),
    cka21 char(1),
    alterado21 varchar(60),
    data22 date,
    ck22 char(1),
    exame22 varchar(60),
    cka22 char(1),
    alterado22 varchar(60),
    data23 date,
    ck23 char(1),
    exame23 varchar(60),
    cka23 char(1),
    alterado23 varchar(60),
    data24 date,
    ck24 char(1),
    exame24 varchar(60),
    cka24 char(1),
    alterado24 varchar(60),
    data25 date,
    ck25 char(1),
    exame25 varchar(60),
    cka25 char(1),
    alterado25 varchar(60),
    data26 date,
    ck26 char(1),
    exame26 varchar(60),
    cka26 char(1),
    alterado26 varchar(60),
    data27 date,
    ck27 char(1),
    exame27 varchar(60),
    cka27 char(1),
    alterado27 varchar(60),
    data28 date,
    ck28 char(1),
    exame28 varchar(60),
    cka28 char(1),
    alterado28 varchar(60),
    data29 date,
    ck29 char(1),
    exame29 varchar(60),
    cka29 char(1),
    alterado29 varchar(60),
    data30 date,
    ck30 char(1),
    exame30 varchar(60),
    cka30 char(1),
    alterado30 varchar(60),
    data31 date,
    ck31 char(1),
    exame31 varchar(60),
    cka31 char(1),
    alterado31 varchar(60),
    data32 date,
    ck32 char(1),
    exame32 varchar(60),
    cka32 char(1),
    alterado32 varchar(60),
    data33 date,
    ck33 char(1),
    exame33 varchar(60),
    cka33 char(1),
    alterado33 varchar(60),
    data34 date,
    ck34 char(1),
    exame34 varchar(60),
    cka34 char(1),
    alterado34 varchar(60),
    data35 date,
    ck35 char(1),
    exame35 varchar(60),
    cka35 char(1),
    alterado35 varchar(60),
    ckanexo1 char(1),
    anexo1 varchar(60),
    ckanexo2 char(1),
    anexo2 varchar(60),
    ckanexo3 char(1),
    anexo3 varchar(60),
    ckanexo4 char(1),
    anexo4 varchar(60),
    ckanexo5 char(1),
    anexo5 varchar(60),
    ckanexo6 char(1),
    anexo6 varchar(60),
    ckanexo7 char(1),
    anexo7 varchar(60),
    ckanexo8 char(1),
    anexo8 varchar(60),
    ckanexo9 char(1),
    anexo9 varchar(60),
    ckanexo10 char(1),
    anexo10 varchar(60),
    ckanexo11 char(1),
    anexo11 varchar(60),
    ckanexo12 char(1),
    anexo12 varchar(60),
    ckanexo13 char(1),
    anexo13 varchar(60),
    ckanexo14 char(1),
    anexo14 varchar(60),
    ckanexo15 char(1),
    anexo15 varchar(60),
    ckanexo16 char(1),
    anexo16 varchar(60),
    ckanexo17 char(1),
    anexo17 varchar(60),
    ckanexo18 char(1),
    anexo18 varchar(60),
    ckq char(1),
    queixap varchar(60),
    ckh char(1),
    historicomedico varchar(300),
    cka char(1),
    alcool char(1),
    fumo char(1),
    ckaf char(1),
    antecedentesfamiliares varchar(300),
    ckc char(1),
    cicatrizes varchar(300),
    ckape char(1),
    antecedentespessoais varchar(300),
    ckaci char(1),
    acidentes varchar(300),
    peso double precision,
    altura double precision,
    imc double precision,
    pa varchar(60),
    fc varchar(60),
    ckod char(1),
    ckoe char(1),
    ckapv char(1),
    molestia varchar(60),
    ckp char(1),
    pele varchar(60),
    ckapa char(1),
    ouvidos varchar(60),
    ckcp char(1),
    cabeca varchar(60),
    ckabd char(1),
    abdomen varchar(300),
    ckap char(1),
    ap varchar(300),
    ckacv char(1),
    apcardio varchar(300),
    ckapn char(1),
    sistemanervoso varchar(100),
    ckagu char(1),
    apuro varchar(100),
    ckaom char(1),
    aosteo varchar(100),
    obsficha varchar(300),
    a char(1),
    i char(1),
    ada char(1),
    aia char(1),
    pair char(1),
    dano char(1),
    historicoav varchar(300),
    conduta varchar(300),
    afastamento char(1),
    dataafastamento date,
    dataretorno date,
    diasperdidos integer)
as
BEGIN
  FOR
    select 
        guias.id_guias,
        guias.numero_guia,
        guias.data_emissao,
        guias.nome_funcionario,
        guias.nome_empresa,
        guias.nome_executante,
        guias.sigla_conselho,
        guias.numero_profissional,
        guias.sigla_unidade,
        guias.codigo_especialidade,
        guias.codigo_cid10_1,
        guias.codigo_cid10_2,
        guias.codigo_cid10_3,
        guias.codigo_cid10_4,
        guias.data_atendimento,
        guias.grau_risco,
        guias.tipo_consulta,
        guias.apto,
        guias.observacao,
        guias.tipo_guia,
        guias.codcliente,
        guias.tipo,
        guias.rg,
        guias.cpf,
        guias.cargo,
        guias.funcao,
        guias.pis,
        guias.data1,
        guias.ck1,
        guias.exame1,
        guias.cka1,
        guias.alterado1,
        guias.data2,
        guias.ck2,
        guias.exame2,
        guias.cka2,
        guias.alterado2,
        guias.data3,
        guias.ck3,
        guias.exame3,
        guias.cka3,
        guias.alterado3,
        guias.data4,
        guias.ck4,
        guias.exame4,
        guias.cka4,
        guias.alterado4,
        guias.data5,
        guias.ck5,
        guias.exame5,
        guias.cka5,
        guias.alterado5,
        guias.data6,
        guias.ck6,
        guias.exame6,
        guias.cka6,
        guias.alterado6,
        guias.data7,
        guias.ck7,
        guias.exame7,
        guias.cka7,
        guias.alterado7,
        guias.data8,
        guias.ck8,
        guias.exame8,
        guias.cka8,
        guias.alterado8,
        guias.data9,
        guias.ck9,
        guias.exame9,
        guias.cka9,
        guias.alterado9,
        guias.data10,
        guias.ck10,
        guias.exame10,
        guias.cka10,
        guias.alterado10,
        guias.data11,
        guias.ck11,
        guias.exame11,
        guias.cka11,
        guias.alterado11,
        guias.data12,
        guias.ck12,
        guias.exame12,
        guias.cka12,
        guias.alterado12,
        guias.data13,
        guias.ck13,
        guias.exame13,
        guias.cka13,
        guias.alterado13,
        guias.data14,
        guias.ck14,
        guias.exame14,
        guias.cka14,
        guias.alterado14,
        guias.data15,
        guias.ck15,
        guias.exame15,
        guias.cka15,
        guias.alterado15,
        guias.data16,
        guias.ck16,
        guias.exame16,
        guias.cka16,
        guias.alterado16,
        guias.data17,
        guias.ck17,
        guias.exame17,
        guias.cka17,
        guias.alterado17,
        guias.data18,
        guias.ck18,
        guias.exame18,
        guias.cka18,
        guias.alterado18,
        guias.data19,
        guias.ck19,
        guias.exame19,
        guias.cka19,
        guias.alterado19,
        guias.data20,
        guias.ck20,
        guias.exame20,
        guias.cka20,
        guias.alterado20,
        guias.data21,
        guias.ck21,
        guias.exame21,
        guias.cka21,
        guias.alterado21,
        guias.data22,
        guias.ck22,
        guias.exame22,
        guias.cka22,
        guias.alterado22,
        guias.data23,
        guias.ck23,
        guias.exame23,
        guias.cka23,
        guias.alterado23,
        guias.data24,
        guias.ck24,
        guias.exame24,
        guias.cka24,
        guias.alterado24,
        guias.data25,
        guias.ck25,
        guias.exame25,
        guias.cka25,
        guias.alterado25,
        guias.data26,
        guias.ck26,
        guias.exame26,
        guias.cka26,
        guias.alterado26,
        guias.data27,
        guias.ck27,
        guias.exame27,
        guias.cka27,
        guias.alterado27,
        guias.data28,
        guias.ck28,
        guias.exame28,
        guias.cka28,
        guias.alterado28,
        guias.data29,
        guias.ck29,
        guias.exame29,
        guias.cka29,
        guias.alterado29,
        guias.data30,
        guias.ck30,
        guias.exame30,
        guias.cka30,
        guias.alterado30,
        guias.data31,
        guias.ck31,
        guias.exame31,
        guias.cka31,
        guias.alterado31,
        guias.data32,
        guias.ck32,
        guias.exame32,
        guias.cka32,
        guias.alterado32,
        guias.data33,
        guias.ck33,
        guias.exame33,
        guias.cka33,
        guias.alterado33,
        guias.data34,
        guias.ck34,
        guias.exame34,
        guias.cka34,
        guias.alterado34,
        guias.data35,
        guias.ck35,
        guias.exame35,
        guias.cka35,
        guias.alterado35,
        guias.ckanexo1,
        guias.anexo1,
        guias.ckanexo2,
        guias.anexo2,
        guias.ckanexo3,
        guias.anexo3,
        guias.ckanexo4,
        guias.anexo4,
        guias.ckanexo5,
        guias.anexo5,
        guias.ckanexo6,
        guias.anexo6,
        guias.ckanexo7,
        guias.anexo7,
        guias.ckanexo8,
        guias.anexo8,
        guias.ckanexo9,
        guias.anexo9,
        guias.ckanexo10,
        guias.anexo10,
        guias.ckanexo11,
        guias.anexo11,
        guias.ckanexo12,
        guias.anexo12,
        guias.ckanexo13,
        guias.anexo13,
        guias.ckanexo14,
        guias.anexo14,
        guias.ckanexo15,
        guias.anexo15,
        guias.ckanexo16,
        guias.anexo16,
        guias.ckanexo17,
        guias.anexo17,
        guias.ckanexo18,
        guias.anexo18,
        guias.ckq,
        guias.queixap,
        guias.ckh,
        guias.historicomedico,
        guias.cka,
        guias.alcool,
        guias.fumo,
        guias.ckaf,
        guias.antecedentesfamiliares,
        guias.ckc,
        guias.cicatrizes,
        guias.ckape,
        guias.antecedentespessoais,
        guias.ckaci,
        guias.acidentes,
        guias.peso,
        guias.altura,
        guias.imc,
        guias.pa,
        guias.fc,
        guias.ckod,
        guias.ckoe,
        guias.ckapv,
        guias.molestia,
        guias.ckp,
        guias.pele,
        guias.ckapa,
        guias.ouvidos,
        guias.ckcp,
        guias.cabeca,
        guias.ckabd,
        guias.abdomen,
        guias.ckap,
        guias.ap,
        guias.ckacv,
        guias.apcardio,
        guias.ckapn,
        guias.sistemanervoso,
        guias.ckagu,
        guias.apuro,
        guias.ckaom,
        guias.aosteo,
        guias.obsficha,
        guias.a,
        guias.i,
        guias.ada,
        guias.aia,
        guias.pair,
        guias.dano,
        guias.historicoav,
        guias.conduta,
        guias.afastamento,
        guias.dataafastamento,
        guias.dataretorno,
        guias.diasperdidos
    from guias
        where 
       (  guias.data_atendimento between :dta1 and :dta2
       and  guias.nome_empresa = :razao
       and (
       cka13 ='S' or cka20 ='S' or cka21 ='S' or cka22 ='S' or cka23 ='S' or cka24 ='S' or cka25 ='S' or cka26 ='S' or cka27 ='S' or cka28 ='S' or cka28 ='S'
  or cka29 ='S' or cka30 ='S' or cka31 ='S' or cka32 ='S' or cka33 ='S' or cka34 ='S' or cka35 ='S' )

       )
    INTO :ID_GUIAS,
         :NUMERO_GUIA,
         :DATA_EMISSAO,
         :NOME_FUNCIONARIO,
         :NOME_EMPRESA,
         :NOME_EXECUTANTE,
         :SIGLA_CONSELHO,
         :NUMERO_PROFISSIONAL,
         :SIGLA_UNIDADE,
         :CODIGO_ESPECIALIDADE,
         :CODIGO_CID10_1,
         :CODIGO_CID10_2,
         :CODIGO_CID10_3,
         :CODIGO_CID10_4,
         :DATA_ATENDIMENTO,
         :GRAU_RISCO,
         :TIPO_CONSULTA,
         :APTO,
         :OBSERVACAO,
         :TIPO_GUIA,
         :CODCLIENTE,
         :TIPO,
         :RG,
         :CPF,
         :CARGO,
         :FUNCAO,
         :PIS,
         :DATA1,
         :CK1,
         :EXAME1,
         :CKA1,
         :ALTERADO1,
         :DATA2,
         :CK2,
         :EXAME2,
         :CKA2,
         :ALTERADO2,
         :DATA3,
         :CK3,
         :EXAME3,
         :CKA3,
         :ALTERADO3,
         :DATA4,
         :CK4,
         :EXAME4,
         :CKA4,
         :ALTERADO4,
         :DATA5,
         :CK5,
         :EXAME5,
         :CKA5,
         :ALTERADO5,
         :DATA6,
         :CK6,
         :EXAME6,
         :CKA6,
         :ALTERADO6,
         :DATA7,
         :CK7,
         :EXAME7,
         :CKA7,
         :ALTERADO7,
         :DATA8,
         :CK8,
         :EXAME8,
         :CKA8,
         :ALTERADO8,
         :DATA9,
         :CK9,
         :EXAME9,
         :CKA9,
         :ALTERADO9,
         :DATA10,
         :CK10,
         :EXAME10,
         :CKA10,
         :ALTERADO10,
         :DATA11,
         :CK11,
         :EXAME11,
         :CKA11,
         :ALTERADO11,
         :DATA12,
         :CK12,
         :EXAME12,
         :CKA12,
         :ALTERADO12,
         :DATA13,
         :CK13,
         :EXAME13,
         :CKA13,
         :ALTERADO13,
         :DATA14,
         :CK14,
         :EXAME14,
         :CKA14,
         :ALTERADO14,
         :DATA15,
         :CK15,
         :EXAME15,
         :CKA15,
         :ALTERADO15,
         :DATA16,
         :CK16,
         :EXAME16,
         :CKA16,
         :ALTERADO16,
         :DATA17,
         :CK17,
         :EXAME17,
         :CKA17,
         :ALTERADO17,
         :DATA18,
         :CK18,
         :EXAME18,
         :CKA18,
         :ALTERADO18,
         :DATA19,
         :CK19,
         :EXAME19,
         :CKA19,
         :ALTERADO19,
         :DATA20,
         :CK20,
         :EXAME20,
         :CKA20,
         :ALTERADO20,
         :DATA21,
         :CK21,
         :EXAME21,
         :CKA21,
         :ALTERADO21,
         :DATA22,
         :CK22,
         :EXAME22,
         :CKA22,
         :ALTERADO22,
         :DATA23,
         :CK23,
         :EXAME23,
         :CKA23,
         :ALTERADO23,
         :DATA24,
         :CK24,
         :EXAME24,
         :CKA24,
         :ALTERADO24,
         :DATA25,
         :CK25,
         :EXAME25,
         :CKA25,
         :ALTERADO25,
         :DATA26,
         :CK26,
         :EXAME26,
         :CKA26,
         :ALTERADO26,
         :DATA27,
         :CK27,
         :EXAME27,
         :CKA27,
         :ALTERADO27,
         :DATA28,
         :CK28,
         :EXAME28,
         :CKA28,
         :ALTERADO28,
         :DATA29,
         :CK29,
         :EXAME29,
         :CKA29,
         :ALTERADO29,
         :DATA30,
         :CK30,
         :EXAME30,
         :CKA30,
         :ALTERADO30,
         :DATA31,
         :CK31,
         :EXAME31,
         :CKA31,
         :ALTERADO31,
         :DATA32,
         :CK32,
         :EXAME32,
         :CKA32,
         :ALTERADO32,
         :DATA33,
         :CK33,
         :EXAME33,
         :CKA33,
         :ALTERADO33,
         :DATA34,
         :CK34,
         :EXAME34,
         :CKA34,
         :ALTERADO34,
         :DATA35,
         :CK35,
         :EXAME35,
         :CKA35,
         :ALTERADO35,
         :CKANEXO1,
         :ANEXO1,
         :CKANEXO2,
         :ANEXO2,
         :CKANEXO3,
         :ANEXO3,
         :CKANEXO4,
         :ANEXO4,
         :CKANEXO5,
         :ANEXO5,
         :CKANEXO6,
         :ANEXO6,
         :CKANEXO7,
         :ANEXO7,
         :CKANEXO8,
         :ANEXO8,
         :CKANEXO9,
         :ANEXO9,
         :CKANEXO10,
         :ANEXO10,
         :CKANEXO11,
         :ANEXO11,
         :CKANEXO12,
         :ANEXO12,
         :CKANEXO13,
         :ANEXO13,
         :CKANEXO14,
         :ANEXO14,
         :CKANEXO15,
         :ANEXO15,
         :CKANEXO16,
         :ANEXO16,
         :CKANEXO17,
         :ANEXO17,
         :CKANEXO18,
         :ANEXO18,
         :CKQ,
         :QUEIXAP,
         :CKH,
         :HISTORICOMEDICO,
         :CKA,
         :ALCOOL,
         :FUMO,
         :CKAF,
         :ANTECEDENTESFAMILIARES,
         :CKC,
         :CICATRIZES,
         :CKAPE,
         :ANTECEDENTESPESSOAIS,
         :CKACI,
         :ACIDENTES,
         :PESO,
         :ALTURA,
         :IMC,
         :PA,
         :FC,
         :CKOD,
         :CKOE,
         :CKAPV,
         :MOLESTIA,
         :CKP,
         :PELE,
         :CKAPA,
         :OUVIDOS,
         :CKCP,
         :CABECA,
         :CKABD,
         :ABDOMEN,
         :CKAP,
         :AP,
         :CKACV,
         :APCARDIO,
         :CKAPN,
         :SISTEMANERVOSO,
         :CKAGU,
         :APURO,
         :CKAOM,
         :AOSTEO,
         :OBSFICHA,
         :A,
         :I,
         :ADA,
         :AIA,
         :PAIR,
         :DANO,
         :HISTORICOAV,
         :CONDUTA,
         :AFASTAMENTO,
         :DATAAFASTAMENTO,
         :DATARETORNO,
         :DIASPERDIDOS
  DO
  BEGIN
    SUSPEND;
  END
END
