CREATE OR ALTER PROCEDURE OEZ_FORN 
returns (
    codfornecedor integer,
    nomefornecedor varchar(60),
    razaosocial varchar(60),
    contato varchar(30),
    tipofirma smallint,
    cpf varchar(14),
    cnpj varchar(18),
    inscestadual varchar(24),
    rg varchar(14),
    segmento smallint,
    regiao smallint,
    limitecredito double precision,
    datacadastro date,
    codusuario integer,
    status smallint,
    homepage varchar(40),
    prazopagamento smallint,
    prazoentrega smallint,
    conta_fornecedor varchar(15),
    cns varchar(7),
    tipodec integer,
    ans varchar(6),
    situacao varchar(1),
    dataevento date,
    etiqueta char(1),
    codendereco integer,
    logradouro varchar(50),
    bairro varchar(30),
    complemento varchar(30),
    cidade varchar(40),
    uf char(2),
    cep varchar(10),
    ddd smallint,
    telefone varchar(9),
    telefone1 varchar(9),
    telefone2 varchar(9),
    fax varchar(9),
    e_mail varchar(30),
    ramal varchar(5),
    tipoend smallint,
    dadosadicionais varchar(200))
as
BEGIN
  FOR
    select 
        fornecedor.codfornecedor,
        fornecedor.nomefornecedor,
        fornecedor.razaosocial,
        fornecedor.contato,
        fornecedor.tipofirma,
        fornecedor.cpf,
        fornecedor.cnpj,
        fornecedor.inscestadual,
        fornecedor.rg,
        fornecedor.segmento,
        fornecedor.regiao,
        fornecedor.limitecredito,
        fornecedor.datacadastro,
        fornecedor.codusuario,
        fornecedor.status,
        fornecedor.homepage,
        fornecedor.prazopagamento,
        fornecedor.prazoentrega,
        fornecedor.conta_fornecedor,
        fornecedor.cns,
        fornecedor.tipodec,
        fornecedor.ans,
        fornecedor.situacao,
        fornecedor.dataevento,
        fornecedor.etiqueta
    from fornecedor
    order by fornecedor.codfornecedor
    INTO :CODFORNECEDOR,
         :NOMEFORNECEDOR,
         :RAZAOSOCIAL,
         :CONTATO,
         :TIPOFIRMA,
         :CPF,
         :CNPJ,
         :INSCESTADUAL,
         :RG,
         :SEGMENTO,
         :REGIAO,
         :LIMITECREDITO,
         :DATACADASTRO,
         :CODUSUARIO,
         :STATUS,
         :HOMEPAGE,
         :PRAZOPAGAMENTO,
         :PRAZOENTREGA,
         :CONTA_FORNECEDOR,
         :CNS,
         :TIPODEC,
         :ANS,
         :SITUACAO,
         :DATAEVENTO,
         :ETIQUETA
  DO
  BEGIN
 select first 1
        enderecofornecedor.codendereco,
        enderecofornecedor.codfornecedor,
        enderecofornecedor.logradouro,
        enderecofornecedor.bairro,
        enderecofornecedor.complemento,
        enderecofornecedor.cidade,
        enderecofornecedor.uf,
        enderecofornecedor.cep,
        enderecofornecedor.ddd,
        enderecofornecedor.telefone,
        enderecofornecedor.telefone1,
        enderecofornecedor.telefone2,
        enderecofornecedor.fax,
        enderecofornecedor.e_mail,
        enderecofornecedor.ramal,
        enderecofornecedor.tipoend,
        enderecofornecedor.dadosadicionais
    from enderecofornecedor
    where enderecofornecedor.codfornecedor = :CODFORNECEDOR and  enderecofornecedor.logradouro is not null
    INTO :CODENDERECO,
         :CODFORNECEDOR,
         :LOGRADOURO,
         :BAIRRO,
         :COMPLEMENTO,
         :CIDADE,
         :UF,
         :CEP,
         :DDD,
         :TELEFONE,
         :TELEFONE1,
         :TELEFONE2,
         :FAX,
         :E_MAIL,
         :RAMAL,
         :TIPOEND,
         :DADOSADICIONAIS ;


    SUSPEND;
  END
END
