CREATE OR ALTER PROCEDURE SP_CONTAS_A_RECEBER (
    DTAINI DATE,
    DTAFIM DATE)
RETURNS (
    DTAEMISSAO DATE,
    DTAVENC DATE,
    CODFORN INTEGER,
    CLIENTES VARCHAR(60),
    DESCRICAO VARCHAR(150),
    VALORRESTO DOUBLE PRECISION,
    VALORPAGO DOUBLE PRECISION,
    CONTACONTABIL VARCHAR(100),
    CAIXA VARCHAR(60),
    CODCONTA VARCHAR(15),
    STATUS VARCHAR(30))
AS
DECLARE VARIABLE CCAIXA INTEGER;
DECLARE VARIABLE N_TITULO VARCHAR(15);
DECLARE VARIABLE CCONTABIL INTEGER;
BEGIN



  /* Lista as contas a receber */


  FOR SELECT rec.EMISSAO ,rec.DATAVENCIMENTO, CAST(rec.CODCLIENTE AS VARCHAR(5)) || '-' ||  cli.NOMECLIENTE,
    rec.HISTORICO, rec.VALOR_RESTO, rec.VALORRECEBIDO, rec.CONTACREDITO,rec.CAIXA, rec.STATUS
    FROM RECEBIMENTO rec, CLIENTES cli where cli.CODCLIENTE = rec.CODCLIENTE
    and ((rec.status = '5-') or (rec.status = '1-')) and rec.DATAVENCIMENTO BETWEEN :DTAINI AND :DTAFIM order by rec.DATAVENCIMENTO
  INTO :DTAEMISSAO, :DTAVENC, :CLIENTES, :DESCRICAO, :VALORRESTO, :VALORPAGO, :CCONTABIL, :CCAIXA, :STATUS
  DO BEGIN

    SELECT NOME, CODREDUZIDO FROM PLANO WHERE CODIGO = :CCONTABIL
    INTO :CONTACONTABIL, :CODCONTA;
    CONTACONTABIL = CODCONTA || '-' || CONTACONTABIL;
    SELECT NOME FROM PLANO WHERE CODIGO = :CCAIXA
    INTO :CAIXA;
    
    IF (STATUS = '1-') THEN
      STATUS = 'Cheque-Pré';

    IF (STATUS = '5-') THEN
      STATUS = 'Pendente';
   

    SUSPEND;
    contacontabil = null;
  END
END
