/******************************************************************************/
/****              Generated by IBExpert 22/02/2012 09:10:32               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE EXPORTA_DMED_S (
    CODCLIENTE       INTEGER,
    RA               VARCHAR(10),
    RAZAOSOCIAL      VARCHAR(50),
    CPF              VARCHAR(18),
    NOMECLIENTE      VARCHAR(50),
    TIPO_DEPENDENTE  VARCHAR(2),
    VLR_MENSAL       DOUBLE PRECISION,
    CLIR             INTEGER,
    NOMEFORNECEDORR  VARCHAR(60),
    TIPOFIRMA        VARCHAR(1),
    CNPJR            VARCHAR(18),
    NOMER            VARCHAR(50),
    VALORR           DOUBLE PRECISION,
    VALORRN          DOUBLE PRECISION,
    VALORRP          DOUBLE PRECISION,
    VALOR_TOTAL      DOUBLE PRECISION,
    CLIRP            INTEGER,
    NOMERP           VARCHAR(50),
    VALORRP1         DOUBLE PRECISION,
    VALOR_RECIBO     DOUBLE PRECISION
);




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

