/******************************************************************************/
/****              Generated by IBExpert 22/02/2012 08:37:54               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE DMED_MENSALIDADE_S (
    CODCLIENTE    INTEGER,
    RA            VARCHAR(10),
    RAZAOSOCIAL   VARCHAR(50),
    VAL           DOUBLE PRECISION,
    FAIXA         INTEGER,
    NOMECLIENTE   VARCHAR(50),
    MES_VCTO      INTEGER,
    MES_PAGTO     INTEGER,
    VLR_PAGO_MES  DOUBLE PRECISION,
    VLR_MENSAL    DOUBLE PRECISION,
    CODMOVIMENTO  INTEGER,
    CODVENDA      INTEGER,
    CPF           VARCHAR(18),
    TIPO          VARCHAR(2),
    DATANASC      DATE,
    TIPO_DEP      VARCHAR(2)
);




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

