/******************************************************************************/
/****              Generated by IBExpert 19/01/2012 17:03:03               ****/
/******************************************************************************/



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE DMED_MENSALIDADE (
    CODCLIENTE    INTEGER,
    RA            VARCHAR(10),
    RAZAOSOCIAL   VARCHAR(50),
    VAL           DOUBLE PRECISION,
    FAIXA         INTEGER,
    NOMECLIENTE   VARCHAR(50),
    MES_VCTO      INTEGER,
    MES_PAGTO     INTEGER,
    VLR_PAGO_MES  DOUBLE PRECISION,
    VLR_MENSAL    DOUBLE PRECISION,
    CODMOVIMENTO  INTEGER,
    CODVENDA      INTEGER,
    CPF           VARCHAR(18)
);




/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

