CREATE OR ALTER trigger novos_socios for clientes
active before update position 0
AS
begin
  INSERT INTO hist_faixa (CODCLIENTE,COD_FAIXA,VALOR,DATA_MOV,SOCIO_NUMERO,DATACADASTRO)
  VALUES (NEW.CODCLIENTE ,NEW.COD_FAIXA,NEW.VALOR_MATRICULA,NEW.DTAALTERA,NEW.NUMERO,NEW.DATACADASTRO);
end
